# Generated by Django 5.2.4 on 2026-02-22 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswer",
            name="date_and_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
